# Generated by Django 3.2.18 on 2023-03-13 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_manager', '0002_auto_20230313_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyschedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='save_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
