# Generated by Django 3.2.18 on 2023-03-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_manager', '0003_auto_20230313_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyschedule',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1),
        ),
    ]
